apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    {{- include "backendnotas.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: {{ .Values.api.image }}:{{ .Values.tag }}
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef: 
                  name: notasMongoUrl
                  key: notas_mongo_url
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              scheme: HTTP
              path: /api/v1/healthz
              port: 3000
          livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "/usr/bin/my-application-jobs --alive"
          initialDelaySeconds: 10
          periodSeconds: 5            initialDelaySeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /api/v1/healthz
              port: 3000            initialDelaySeconds: 10 
          readinessProbe: 
            initialDelaySeconds: 10 
            periodSeconds: 1 
            httpGet: 
              path: /api/v1/healthz 
              port: 3000 
          livenessProbe: 
            initialDelaySeconds: 10  
            periodSeconds: 1 
            httpGet: 
              path: /api/v1/healthz 
              port: 3000 