apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    {{- include "backendnotas.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: {{ .Values.api.image }}:{{ .Values.tag }}
          env:
            - name: BACKENDNOTAS_MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: backendnotas_mongo_url
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /api/v1/healthz
              port: 3000
          livenessProbe:
            periodSeconds: 5
            httpGet:
              path: /api/v1/healthz
              port: 3000